name: aorta
description: "Flutter Test project for Aorta"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.9.2

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  bloc_test: ^10.0.0
  auto_route: ^10.2.0
  qr_code_scanner_plus: ^2.0.14
  flutter_screenutil: ^5.9.3
  currency_text_input_formatter: ^2.3.0
  pinput: ^5.0.2
  google_fonts: ^6.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  upgrader: ^12.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  toastification: ^3.0.3
  path_provider: ^2.1.5
  internet_connection_checker: ^1.0.0+1
  skeletonizer: ^2.1.0+1
  font_awesome_flutter: ^10.12.0
  timeago: ^3.7.1
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  cached_network_image:
    git:
      url: https://github.com/mutant0113/flutter_cached_network_image.git
      path: cached_network_image
      ref: fix_ios_image_upload_failed_due_to_loss_of_GPU_access
  fpdart: ^1.1.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path: ^1.9.1
  sqflite: ^2.4.2
  json_reflectable: ^1.0.1
  json_annotation: ^4.9.0
  hugeicons: ^1.1.2
  rxdart: ^0.28.0
  get_secure_storage: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.5
  lean_builder: ^0.1.2
  drift_dev: ^2.29.0
  build_runner: ^2.7.1
  mocktail: ^1.0.4
  json_serializable: ^6.11.1

flutter:
  generate: true
  uses-material-design: true

