name: Sauce Labs Lightweight Trigger Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sauce-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Node dependencies
      working-directory: test/appium_saucelabs_cicd_integrationTest
      run: npm ci

    - name: Run tests on Sauce Labs
      working-directory: test/appium_saucelabs_cicd_integrationTest
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npx wdio run wdio.conf.js --spec test/specs/aorta.js
